### ISSUE TITLE
create a pre-commit hook 

### ISSUE THREAD

**Issue by alex-rakowski** [hauntsaninja/no_implicit_optional#16]
This would be great to have as a pre-commit hook. I've forked the repo and have it working, but it would be better to come from the main repo rather than me keeping mine in sync with this.  

you can test this pre-commit by adding this to your `pre-commit-config.yaml`:
```yaml
  -   repo: https://github.com/alex-rakowski/no_implicit_optional # This will change to this repo
      # rev: 0.1.5
      rev: 8147e918d73b2c26280e40fdb0106011daad91de # from a particular commit
      hooks:
      -   id: no_implicit_optional_checker
```
To use a specified version rather than a commit hash, it would need tagged releases. 

I can PR in the changes if there's interest in your end
